const defaultStore = {};

const defaultStorage = {};

const defaultFaction = {
    _id: '',
    name: '',
    bank: 0.0,
    canDisband: false,
    type: 'state',
    members: [],
    ranks: [],
    availableActions: [''],
    actions: {},
    tickActions: [''],
    vehicles: [],
    storages: [],
    settings: {
        position: {
            x: 0.0,
            y: 0.0,
            z: 0.0,
        },
        parkingSpots: [
            {
                pos: { x: 0.0, y: 0.0, z: 0.0 },
                rot: { x: 0.0, y: 0.0, z: 0.0 },
            },
        ],
        vehicles: [
            {
                model: '',
                price: 0.0,
            },
        ],
        maxVehicles: 0,
        blip: 0,
        blipColor: 0,
        motd: '',
    },
};

const defaultGarage = {
    position: { x: 0.0, y: 0.0, z: 0.0 },
    type: 'boat, aircraft, vehicle or train',
    index: 'name-of-garage',
    parking: [
        {
            position: {
                x: 0.0,
                y: 0.0,
                z: 0.0,
            },
            rotation: {
                x: 0.0,
                y: 0.0,
                z: 0.0,
            },
        },
    ],
};

const defaultInterior = {
    name: '',
    uid: '',
    outside: { x: 0, y: 0, z: 0 },
    inside: { x: 0, y: 0, z: 0 },
    objects: [],
    system: 'NONE',
    isUnlocked: true,
    interiorID: -1,
    ipl: '',
    entitySets: [{ name: '', active: true }],
    price: 0.0,
};

const defaultItem = {
    name: ``,
    description: ``,
    dbName: '',
    icon: '',
    slot: 0,
    sell: 1.25,
    buy: 2.5,
    maxStack: 10,
    quantity: 1,
    rarity: 1,
    behavior: 0,
    data: {
        event: '',
        amount: 5,
        sound: 'item_',
    },
    version: 1,
};

const defaultCharacter = {
    _id: '',
    pos: {
        x: 415.6747131347656,
        y: -976.4703369140625,
        z: 29.4315185546875,
    },
    cash: 113368.84,
    appearance: {
        eyebrowsOpacity: 1,
        skinMix: 0.5,
        chestHair: 0,
        chestHairColor1: 5,
        opacityOverlays: [
            {
                id: 0,
                opacity: 0,
                value: 0,
            },
            {
                id: 3,
                opacity: 0,
                value: 0,
            },
            {
                id: 6,
                opacity: 0,
                value: 0,
            },
            {
                id: 7,
                opacity: 0,
                value: 0,
            },
            {
                id: 9,
                opacity: 0,
                value: 0,
            },
            {
                id: 11,
                opacity: 0,
                value: 0,
            },
        ],
        chestHairOpacity: 0,
        colorOverlays: [
            {
                color1: 0,
                opacity: 0,
                color2: 0,
                id: 4,
                value: 0,
            },
            {
                color1: 0,
                id: 5,
                opacity: 0,
                value: 0,
            },
            {
                color1: 0,
                id: 8,
                opacity: 0,
                value: 0,
            },
        ],
        eyebrows: 1,
        eyes: 3,
        eyebrowsColor1: 5,
        facialHairOpacity: 1,
        faceFather: 10,
        faceMix: 0.5,
        faceMother: 21,
        facialHair: 2,
        facialHairColor1: 5,
        hair: 2,
        hairColor1: 5,
        hairColor2: 44,
        hairOverlay: {
            collection: 'mpbiker_overlays',
            overlay: 'MP_Biker_Hair_002_M',
        },
        sex: 1,
        skinFather: 10,
        skinMother: 21,
        structure: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        hairDlc: 2939825043,
    },
    info: {
        age: '18-7-1990',
        gender: 'Mann',
        name: 'Kurt_Krabowski',
    },
    food: 85.70000000000081,
    water: 77.12000000000049,
    isDead: false,
    health: 200,
    armour: 0,
    hours: 34.56666666666599,
    wanted: 0,
    account_id: '63309e9a71ae21d7a4f87d05',
    name: 'Kurt_Krabowski',
    character_id: 1,
    equipment: [
        {
            name: 'Bottoms',
            description: '',
            icon: 'bottoms',
            slot: 3,
            sell: 0,
            buy: 0,
            quantity: 1,
            behavior: 13,
            data: {
                drawables: [4],
                ids: [4],
                textures: [0],
                isProp: false,
                sex: 1,
                dlcHashes: [2398078303],
            },
            equipment: 3,
        },
        {
            name: 'Shoes',
            description: '',
            icon: 'shoes',
            slot: 4,
            sell: 0,
            buy: 0,
            quantity: 1,
            behavior: 13,
            data: {
                drawables: [0],
                ids: [6],
                textures: [5],
                isProp: false,
                sex: 1,
                dlcHashes: [3572380696],
            },
            equipment: 4,
        },
        {
            name: 'Accessory',
            description: '',
            icon: 'accessory',
            slot: 11,
            sell: 0,
            buy: 0,
            quantity: 1,
            behavior: 13,
            data: {
                drawables: [3],
                ids: [7],
                textures: [6],
                isProp: false,
                sex: 1,
                dlcHashes: [1716449931],
            },
            equipment: 11,
        },
        {
            name: 'Earrings / Ear Pieces',
            description: '',
            icon: 'ear',
            slot: 6,
            sell: 0,
            buy: 0,
            quantity: 1,
            behavior: 13,
            data: {
                drawables: [0],
                ids: [2],
                textures: [0],
                isProp: true,
                sex: 1,
                dlcHashes: [2398078303],
            },
            equipment: 6,
        },
        {
            name: 'Glasses',
            description: '',
            icon: 'glasses',
            slot: 5,
            sell: 0,
            buy: 0,
            quantity: 1,
            behavior: 13,
            data: {
                drawables: [5],
                ids: [1],
                textures: [3],
                isProp: true,
                sex: 1,
                dlcHashes: [0],
            },
            equipment: 5,
        },
        {
            name: 'Wrist Bracelet',
            description: '',
            icon: 'bracelet',
            slot: 10,
            sell: 0,
            buy: 0,
            quantity: 1,
            behavior: 13,
            data: {
                drawables: [2],
                ids: [7],
                textures: [0],
                isProp: true,
                sex: 1,
                dlcHashes: [2939825043],
            },
            equipment: 10,
        },
        {
            name: 'Wrist Watch',
            description: '',
            icon: 'watch',
            slot: 9,
            sell: 0,
            buy: 0,
            quantity: 1,
            behavior: 13,
            data: {
                drawables: [0],
                ids: [6],
                textures: [0],
                isProp: true,
                sex: 1,
                dlcHashes: [1716449931],
            },
            equipment: 9,
        },
        {
            name: 'Shirt',
            description: '',
            icon: 'shirt',
            slot: 2,
            sell: 0,
            buy: 0,
            quantity: 1,
            behavior: 13,
            data: {
                drawables: [1, 0, 7],
                ids: [11, 8, 3],
                textures: [0, 0, 0],
                isProp: false,
                sex: 1,
                dlcHashes: [3637654078, 3231060067, 2398078303],
            },
            equipment: 2,
        },
    ],
    inventory: [
        {
            name: 'Cola',
            description: 'Eine Flasche erfrischende Cola.',
            icon: 'crate',
            slot: 0,
            quantity: 6,
            buy: 2.18,
            sell: 1.09,
            behavior: 151,
            data: {
                amount: 25,
                event: 'effect:Water',
                sound: 'item_drink',
            },
        },
        {
            name: 'Cheeseburger',
            description: 'Ein leckerer Cheeseburger.',
            icon: 'crate',
            slot: 1,
            quantity: 6,
            buy: 2.5,
            sell: 1.25,
            behavior: 151,
            data: {
                amount: 25,
                event: 'effect:Food',
                sound: 'item_eat',
            },
        },
    ],
    toolbar: [],
    banned: {
        state: false,
        reason: '',
    },
    faction: null,
};

const defaultBank = {
    _id: '',
    amount: 0.0,
    logs: [],
    iban: '',
    name: '',
    type: '',
    owner: ''
};

export default {
    defaultStore,
    defaultInterior,
    defaultItem,
    defaultGarage,
    defaultStorage,
    defaultFaction,
    defaultCharacter,
    defaultBank
};
